---
- hosts: localhost
  gather_facts: yes
  roles:
   - common
   - vm

- hosts: azure_vms
  gather_facts: no
  tasks:
  - name: Install notepadplusplus on the newly provitioned server.
    win_chocolatey:
      name: notepadplusplus
      version: '6.6'
