#Provitioning the infra and Virtual machine
---
- hosts: localhost
  gather_facts: yes
  roles:
   - common
   - vm
#Install some softwears in the newly provitioned server 
- hosts: azure_vms
  gather_facts: no
  tasks:
  - name: Install notepadplusplus on the newly provitioned server.
    win_chocolatey:
      name: notepadplusplus
      version: '6.6'
