root@IcingaMaster:/home/rohit.sinhalala/playbooks/sample_app# cat roles/common/tasks/main.yaml
---
- name: Get facts for one resource group
  azure_rm_resourcegroup_facts:
    name: "{{ rg_name }}"
  register: output
- name: save the output to local file
  local_action: copy content={{ output }} dest=/tmp/output
- name: cat the output
  shell: cat /tmp/output
  register: file_output

- name: Create a resource group
  azure_rm_resourcegroup:
   name: "{{ rg_name }}"
   location: "{{ location }}"
   state: present
#  when: output.ansible_facts.azure_resourcegroups[0].properties.provisioningState is equal to 'Succeeded'
  when: file_output.stdout.find('{{ rg_name }}') == -1

- name: Create a virtual network
  azure_rm_virtualnetwork:
   name: "{{ vitual_network }}"
   resource_group: "{{ rg_name }}"
   address_prefixes_cidr:
     - "{{ CIDR }}"
- name: Create a subnet
  azure_rm_subnet:
   name: "{{ subnet }}"
   virtual_network_name: "{{ vitual_network }}"
   resource_group: "{{ rg_name }}"
   address_prefix_cidr: "{{ subnet_CIDR }}"
- name: Create network windows base security groups
  azure_rm_securitygroup:
    resource_group: "{{ rg_name }}"
    name: windows_base
    purge_rules: yes
    rules:
     - name: 'AllowRDP'
       protocol: Tcp
       source_address_prefix: 0.0.0.0/0
       destination_port_range: 3389
       access: Allow
       priority: 100
       direction: Inbound
     - name: 'AllowWinRM'
       protocol: Tcp
       source_address_prefix: 0.0.0.0/0
       destination_port_range: 5986
       priority: 102
       direction: Inbound
     - name: 'DenyAll'
       protocol: Tcp
       source_address_prefix: 0.0.0.0/0
       destination_port_range: 0-65535
       priority: 103
       direction: Inbound
- name: Create WMI Security group
  azure_rm_securitygroup:
    resource_group: "{{ rg_name }}"
    name: WMI
    purge_rules: yes
    rules:
     - name: 'Microsoft_DS'
       protocol: Tcp
       source_address_prefix: 0.0.0.0/0
       destination_port_range: 445
       access: Allow
       priority: 100
       direction: Inbound
     - name: 'AllowWMIfixed'
       protocol: Tcp
       source_address_prefix: 0.0.0.0/0
       destination_port_range: 24158
       priority: 102
       access: Allow
       direction: Inbound
     - name: 'AllowWMI'
       protocol: Tcp
       source_address_prefix: 0.0.0.0/0
       destination_port_range: 135
       access: Allow
       priority: 103
       direction: Inbound
     - name: 'DenyAll'
       protocol: Tcp
       source_address_prefix: 0.0.0.0/0
       destination_port_range: 0-65535
       priority: 104
       direction: Inbound
